accounts/urls.py
from django.urls import path
from . import views
# under allauth.account
from django.contrib.auth.views import * 

app_name = "accounts"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.update_profile, name='profile'),

    path('addusers/', views.addusers, name='add-users'),

    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
]

api/urls.py
# api.urls

from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

# app_name = 'api'
# naming this app BREAKS DATATABLES IN DATASET BROWSE

urlpatterns = [

    # database places
    path('db/',views.SearchAPIView.as_view(),name='api-search'),
    # index docs
    path('index/',views.IndexAPIView.as_view(),name='api-index-search'),
    # index docs for remote
    path('remote/',views.RemoteIndexAPIView.as_view(),name='api-remote-search'),
    # spatial (nearby or bbox)
    path('spatial/', views.SpatialAPIView.as_view(), name='api-spatial'),

    # *** DATASETS ***

    # use: filter public datasets by id, label, term
    # 2022-09 name conflict with new remote api
    # path('datasets/', views.DatasetAPIView.as_view(), name='dataset-list'),
    path('datasets/', views.DatasetAPIView.as_view(), name='ds-list'),


    # *** PLACES ***
        
    # use: single place for ds_browse:: PlaceSerializer
    # also search.html if search scope = 'db'
    path('place/<int:pk>/', views.PlaceDetailAPIView.as_view(), name='place-detail'),

    # single place for record comparison in ds_update
    path('place_compare/<int:pk>/', views.PlaceCompareAPIView.as_view(), name='place-compare'),

    # places in a dataset
    # use: drf table in ds_browse  :: PlaceSerializer
    path('placetable/', views.PlaceTableViewSet.as_view({'get':'list'}), name='place-table'),
    # places in a collection
    path('placetable_coll/', views.PlaceTableCollViewSet.as_view({'get':'list'}), name='place-table-coll'), 

    # TODO: place/<str:dslabel>/<str:src_id>
    path('place/<str:dslabel>/<str:src_id>/', views.PlaceDetailSourceAPIView.as_view(),name='place-detail-src'), 


    # 
    # *** GEOMETRY ***
    # 
    # use: map in ds_browse, ds_places, collection_places :: PlaceGeomSerializer
    path('geoms/', views.GeomViewSet.as_view({'get':'list'}), name='geom-list'),
    # use: heatmap sources for collection_places.html
    path('geojson/', views.GeoJSONAPIView.as_view(), name='geojson'),    

    
    # 
    # *** AREAS ***
    # 
    # use: single area in dataset.html#addtask
    path('area/<int:pk>/', views.AreaViewSet.as_view({'get': 'retrieve'}),name='area-detail'),
    # returns list of simple objects (id, title) for home>autocomplete
    path('area_list/', views.AreaListView.as_view(),name='area-list'),
    # geojson for api
    path('area_features/', views.AreaFeaturesView.as_view(),name='area-features'), 
    
    # only UN regions, for teaching
    path('regions/', views.RegionViewSet.as_view(), name='regions'),

    # 
    # *** USERS ***
    #   
    path('users/', views.UserList.as_view(),name='user-list'),
    path('user/<int:pk>/', views.UserDetail.as_view(),name='user-detail'),
    
    # 
    # *** INDEX ***
    # 
    # use: single union record in usingapi.html ?idx=whg&_id={whg_id}
    # TODO: build from place_id
    #url('union/', views.indexAPIView.as_view(), name='union_api')
    
]

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'tsv', 'geojson'])

collection/urls.py
# collection.urls

from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from . import views
from traces.views import get_form, annotate

# area actions
app_name='collection'

urlpatterns = [

    # DATASET collections (datasets only)
    path('create_ds/', views.DatasetCollectionCreateView.as_view(), name='ds-collection-create'),
    path('<int:id>/update_ds', views.DatasetCollectionUpdateView.as_view(), name='ds-collection-update'),
    path('<int:pk>/summary_ds', views.DatasetCollectionSummaryView.as_view(), name='ds-collection-summary'),
    path('<int:id>/browse_ds', views.DatasetCollectionBrowseView.as_view(), name='ds-collection-browse'),

    # PLACE collections (datasets, indiv places, annotations, 'authored')
    path('create_pl/', views.PlaceCollectionCreateView.as_view(), name='place-collection-create'),
    path('<int:id>/update_pl', views.PlaceCollectionUpdateView.as_view(), name='place-collection-update'),
    path('<int:id>/browse_pl', views.PlaceCollectionBrowseView.as_view(), name='place-collection-browse'),
    path('flash_create/', views.flash_collection_create, name="collection-create-flash"),

    path('<int:id>/delete', views.CollectionDeleteView.as_view(), name='collection-delete'),

    # UTILITY
    path('list_ds/', views.ListDatasetView.as_view(), name='list-ds'),
    path('add_ds/<int:coll_id>/<int:ds_id>', views.add_dataset, name='add-ds'),
    path('remove_ds/<int:coll_id>/<int:ds_id>', views.remove_dataset, name='remove-ds'),

    path('add_places/', views.add_places, name="collection-add-places"),
    path('remove_places/', views.remove_places, name="collection-remove-places"),
    path('create_link/', views.create_link, name="collection-create-link"),
    path('remove_link/<int:id>/', views.remove_link, name="remove-link"),

    # function-based views to process a trace annotation
    path('<int:id>/annotate', csrf_exempt(annotate), name="collection-annotate"),
    path('annoform/', get_form, name="get_form"),

    # switch off active bit
    path('inactive/', views.inactive, name="collection-inactive"),

    path('<int:id>/geojson/', views.fetch_geojson_coll, name="geojson-coll"),

    ## COLLABORATORS
    # add CollectionUser collaborator
    path('collab-add/<int:collid>', views.collab_add, name="coll-collab-add"),

    # delete CollectionUser collaborator
    path('collab-delete/<int:uid>/<int:collid>', views.collab_delete, name="coll-collab-delete"),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

datasets/urls.py
# datasets.urls

from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views
from datasets.utils import download_file, UpdateCountsView, download_augmented, \
  fetch_geojson_ds, downloader, fetch_geojson_flat, downloadLP7

# dataset actions
app_name='datasets'
urlpatterns = [

  ## BASICS: create from upload, create empty, delete
  path('create/', views.DatasetCreateView.as_view(), name='dataset-create'),
  path('createnew/', views.DatasetCreateView.as_view(), name='dataset-create'),
  path('create_empty/', views.DatasetCreateEmptyView.as_view(), name='dataset-create-empty'),
  path('<int:id>/delete', views.DatasetDeleteView.as_view(), name='dataset-delete'),

  # insert validated delimited file data to db (csv, tsv, spreadsheet)
  path('<int:pk>/insert_tsv/', views.ds_insert_tsv, name="ds_insert_tsv"),

  # insert validated lpf file data to db
  path('<int:pk>/insert_lpf/', views.ds_insert_lpf, name="ds_insert_lpf"),

  # upload excel
  path('xl/', views.xl_upload, name='xl-upload'),

  ## MANAGE/VIEW
  # dataset owner pages (tabs); names correspond to template names
  path('<int:id>/summary', views.DatasetSummaryView.as_view(), name='ds_summary'),
  path('<int:id>/browse', views.DatasetBrowseView.as_view(), name='ds_browse'),
  path('<int:id>/reconcile', views.DatasetReconcileView.as_view(), name='ds_reconcile'),
  path('<int:id>/collab', views.DatasetCollabView.as_view(), name='ds_collab'),
  path('<int:id>/addtask', views.DatasetAddTaskView.as_view(), name='ds_addtask'),
  path('<int:id>/log', views.DatasetLogView.as_view(), name='ds_log'),

  # public dataset pages (tabs): metadata, browse
  path('<int:pk>', views.DatasetPublicView.as_view(), name='ds_meta'),
  path('<int:id>/places', views.DatasetPlacesView.as_view(), name='ds_places'),

  ## DOWNLOADS
  # one-off for LP7
  path('download_lp7/', downloadLP7, name='download_lp7'),

  # download latest file, as uploaded
  path('<int:id>/file/', download_file, name="dl-file"), #

  # initiate downloads of augmented datasets via celery task (called from ajax)
  path('dlcelery/', downloader, name='dl_celery'),
  ## DEPRECATing download augmented dataset
  path('<int:id>/augmented/<str:format>', download_augmented, name="dl-aug"), #

  ## UPDATES (in progress)
  path('compare/', views.ds_compare, name='dataset-compare'),
  path('update/', views.ds_update, name='dataset-update'),

  ## RECONCILIATION/REVIEW
  # initiate reconciliation
  path('<int:pk>/recon/', views.ds_recon, name="ds_recon"), # form submit

  # review, validate hits
  path('<int:pk>/review/<str:tid>/<str:passnum>', views.review, name="review"),

  # direct load of deferred place to review screen
  path('<int:pk>/review/<str:tid>/<str:pid>', views.review, name="review"),

  # accept any unreviewed wikidata pass0 hits from given task
  path('wd_pass0/<str:tid>', views.write_wd_pass0, name="wd_pass0"),
  path('idx_pass0/<str:tid>', views.write_idx_pass0, name="idx_pass0"),

  # delete TaskResult & associated hits
  path('task-delete/<str:tid>/<str:scope>', views.task_delete, name="task-delete"),

  # undo last save in review
  path('match-undo/<int:ds>/<str:tid>/<int:pid>', views.match_undo, name="match-undo"),

  # refresh reconciliation counts (ds.id from $.get)
  path('updatecounts/', UpdateCountsView.as_view(), name='update_counts'),

  ## COLLABORATORS
  # add DatasetUser collaborator
  path('collab-add/<int:dsid>/<str:v>', views.collab_add, name="collab-add"),

  # delete DatasetUser collaborator
  path('collab-delete/<int:uid>/<int:dsid>/<str:v>', views.collab_delete, name="collab-delete"),

  ## GEOMETRY
  path('<int:dsid>/geojson/', fetch_geojson_ds, name="geojson"),
  path('<int:dsid>/geojson_flat/', fetch_geojson_flat, name="geojson-flat"),

  # list places in a dataset; for physical geog layers
  path('<str:label>/places/', views.ds_list, name='ds_list'),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

whg/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic.base import TemplateView

from main import views
from datasets.views import PublicListsView, DataListsView
from resources.views import TeachingPortalView

app_name='main'
#handler404 = 'datasets.views.handler404',
handler500 = 'main.views.custom_error_view'

urlpatterns = [
    path('', views.Home2b.as_view(), name="home"),
    
    path('libre/', views.LibreView.as_view(), name='libre'),
    
    # apps
    path('search/', include('search.urls')),
    path('datasets/', include('datasets.urls')),
    path('areas/', include('areas.urls')),
    path('collections/', include('collection.urls')),
    path('places/', include('places.urls')),
    path('elastic/', include('elastic.urls')),
    path('tutorials/', include('main.urls')),
    path('resources/', include('resources.urls')),
    path('teaching/', TeachingPortalView.as_view(), name="teaching-page"),

    # DEPRECATED
    # path('dashboard/', DashboardView.as_view(), name='dashboard'),

    ## DATA "DASHBOARD" LIST VIEWS
    # reverse name is parameter to DataListsView()
    path('mydata/', DataListsView.as_view(), name='data-datasets'),
    path('mycollections/', DataListsView.as_view(), name='data-collections'),
    path('mystudyareas/', DataListsView.as_view(), name='data-areas'),
    path('resourcelist/', DataListsView.as_view(), name='data-resources'),

    path('public_data/', PublicListsView.as_view(), name='public-lists'),

    # static content
    path('about/', TemplateView.as_view(template_name="main/about.html"), name="about"),
    path('contributing/', TemplateView.as_view(template_name="main/contributing.html"), name="contributing"),
    path('credits/', TemplateView.as_view(template_name="main/credits.html"), name="credits"),
    path('licensing/', TemplateView.as_view(template_name="main/licensing.html"), name="licensing"),
    path('system/', TemplateView.as_view(template_name="main/system.html"), name="system"),
    path('usingapi/', TemplateView.as_view(template_name="main/usingapi.html"), name="usingapi"),
    path('tinymce/', include('tinymce.urls')),

    path('comment/<int:rec_id>', views.CommentCreateView.as_view(), name='comment-create'),
    path('contact/', views.contact_view, name='contact'),
    path('success/', views.contact_success_view, name='success'),
    path('status/', views.status_view, name='status'),
    

    # backend stuff
    path('api/', include('api.urls')),
    path('remote/', include('remote.urls')),
    path('accounts/', include('allauth.urls')),
    #path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    # path('captcha/', include('captcha.urls')),

    re_path(r'^celery-progress/', include('celery_progress.urls')),  # the endpoint is configurable
    

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth import get_user_model
User = get_user_model()

# from accounts.models import Profile

class LoginForm(forms.Form):
    email = forms.CharField(max_length=255, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)

    def clean(self):
        name = self.cleaned_data.get('name')
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        return self.cleaned_data

    def login(self, request):
        name = self.cleaned_data.get('name')
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        return user

# used to edit
class UserModelForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ('email', 'name', 'affiliation', 'role')
        exclude = ('password',)

        widgets = {
            'email': forms.TextInput(attrs={'size': 30}),
            'name': forms.TextInput(attrs={'size': 30}),
            'affiliation': forms.TextInput(attrs={'size': 30}),
        }

# not in use
# class ProfileModelForm(forms.ModelForm):
#
#     class Meta:
#         model = User
#         #fields = ('name','affiliation','web_page','user_type')
#         #fields = ('affiliation','web_page','user_type')
#         fields = ('name', 'affiliation', )
#         widgets = {
#             'name': forms.TextInput(attrs={'size': 40}),
#             'affiliation': forms.TextInput(attrs={'size': 40}),
#             # 'web_page': forms.TextInput(attrs={'size': 60}),
#             'password': forms.PasswordInput(attrs={'size': 40}),
#         }

accounts/templates/accounts/login.html
{% extends 'main/base.html' %}

{% block title %}<title>WHG::Login</title>{% endblock %}

{% block content %}
{% load static %}
  <div class="container">
    <div class="d-flex justify-content-center mt-3">
      <div>
        <h2>Login</h2>
        <form method="post" action="{% url 'accounts:login' %}">
          {% csrf_token %}
          Email:<br/>
          <input type="text" name="email" size = 30 />
{#          Username:<br/>#}
{#          <input type="text" name="username" />#}
          <br/>
          Password:<br/>
          <input type="password" name="password" size = 30/>
          <br/><br/>
          <input class="btn btn-primary" type="submit" value="Login" />
        </form>
        <p class="mt-2">Not a user yet? <a href="{% url 'accounts:register' %}">Register first</a></p>
        <p class="mt-2"><a href="{% url 'accounts:password_reset' %}">Forgot password?</a></p>
        {% if error %}
          <p style="color:red">{{ error }}</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'main/base.html' %}
{% block extra_head %}
{#    <style>#}
{#        th, td {#}
{#            padding: 2px 10px;#}
{#        }#}
{#    </style>#}
{% endblock %}
{% block content %}

<div class="container">
	<h3 class="text-center">My Dashboard</h3>
	<div class="row">
    <div class="col-6" id="dash_left">
			<form id="profile_form" method="POST" action="{% url 'accounts:profile' %}" enctype="multipart/form-data">
	    {% csrf_token %}
	    {{ user_form.errors }}
	    {{ profile_form.errors }}
	    {{ user_form.non_field_errors }}
	    {{ profile_form.non_field_errors }}
      <h5 class="profile-header">Profile
        <span id="edit_link" class="small float-end">
        <a href="#"><i class="fas fa-edit linky fa-xs"></i></a>
        </span>
      </h5>
      <span class="hidden">{{ user_form.email }}</span>
      <span class="hidden">{{ user_form.password }}</span>
      <span class="hidden">{{ user_form.role }}</span>
      <table>
            <tbody>
            <tr>
                <td class="float-end pe-3 strong">Login email</td>
                <td>{{ user_form.email.value }}</td>
            </tr>
            <tr>
                <td class="float-end pe-3 strong">Full name</td>
                <td class="strong-red">{{ user_form.name.value }}</td>
            </tr>
            <tr>
                <td class="float-end pe-3 strong">Affiliation</td>
                <td>{{ user_form.affiliation.value }}</td>
            </tr>
            <tr>
                <td class="float-end pe-3 strong">WHG role (id)</td>
                <td class="ital">
                    {% if user.is_superuser %}superuser{% else %}
                        {{ user_form.role.value }}{% endif %} ({{ user.id }})
                </td>
            </tr>
            </tbody>
        </table>
      <div id="edit_profile" class="hidden">
	      <hr/>
        <table>
          <tbody>
          <tr>
            <td class="float-end pe-3 strong">Name</td>
            <td>{{ user_form.name }}</td>
          </tr>
          <tr>
	          <td class="float-end pe-3 strong">Affiliation</td>
	          <td>{{ user_form.affiliation }}</td>
          </tr>
          </tbody>
        </table>
        <div class="ps-2">
          <input class="btn btn-primary btn-sm mt-3" type="submit" value="Save"/>
          <span class="ms-2" style="vertical-align:bottom;">
            <a href="{% url 'accounts:profile' %}">Cancel</a>
          </span>
        </div>
      </div> <!-- #editProfile -->
			</form>
    </div>
    <div class="col-6" id="data_right">
	    <h5 class="profile-header">Collections and Datasets</h5>
	    <table class="w-100">
        <tbody>
        {% if user_form.role.value == 'group_leader' or user.is_superuser %}
	        <tr style="background-color: honeydew;">
		        <td class="pe-3" style="vertical-align:top;"> Collection groups
	            <p class="mt-0 text-secondary small">
		            <i class="fas fa-plus-square linky"></i>
		            <a href="{% url 'collection:collection-group-create' %}" id="a_creategroup">new</a>
	            </p>
	          </td>
	          <td style="vertical-align: top;">
	            {% for cg in user.collection_groups.all %}
	              <a href="{% url 'collection:collection-group-update' id=cg.id %}">{{ cg.title }}</a><br/>
	              <span class="small">({{ cg.members.count }} members)</span><br/>
	            {% endfor %}
	          </td>
	        </tr>
	        <tr style="border-bottom: gainsboro 1px solid;">
	          <td >&nbsp;</td> <td></td>
	        </tr>
	        {% if context.groups_owned|length > 0 %}
	        <tr>
	          <td class="pe-3" style="vertical-align: top">System groups</td>
	          <td id="grouplist">
	            {% for g in context.groups_owned %}
	              <span class="ital">{{ g.name }}</span><br/>
	              {% if not forloop.last %} {% endif %}
	            {% endfor %}
	          </td>
	        </tr>
	        {% endif %}
        {% endif %} {# group_leqder #}
        {% if context.mygroups|length > 0 %}
          <tr>
            <td class="pe-3 strong" style="vertical-align: top;">Collection Groups</td>
            <td>
              {% for g in context.mygroups %}
	              <b><a href="{% url 'collection:collection-group-detail' g.id %}">{{ g }}</a></b>
	              <br/>
              {% endfor %}
            </td>
          </tr>
        {% endif %}
        {% with owned=context.coll_owned collabs=context.coll_collab %}
        {% if owned|length > 0 or collabs|length > 0 %}
          <tr>
            <td class="strong" style="vertical-align: top;">My Place Collections</td>
	          <td>
              {% for c in owned %}
	              <span><a href="{% url 'collection:place-collection-update' c.id %}">{{ c.title }}</a></span><br/>
              {% endfor %}
	          </td>
          </tr>
	        <tr>
	          <td class="strong" style="vertical-align: top;">Collection<br/>collaborations</td>
		        <td>
              {% for c in collabs %}
	              <span><a href="{% url 'collection:place-collection-update' c.collection.id %}">{{ c.collection.title }}</a></span><br/>
              {% endfor %}
            </td>
          </tr>
        {% endif %}
        {% endwith %}
        {% if context.ds_owned|length > 0 %}
          <tr>
            <td class="pe-3 strong" style="vertical-align: top;">Datasets</td>
            <td>
              {% for ds in context.ds_owned %}
                  <b><a href="{% url 'datasets:ds_summary' ds.0 %}">{{ ds.1 }}</a></b> ({{ ds.0 }}
                  , {{ ds.2 }})<br/>
              {% endfor %}
              {% for ds in context.ds_collabs %}
                  <b><a href="{% url 'datasets:ds_summary' ds.0 %}">{{ ds.1 }}</a></b> ({{ ds.0 }}
                  , {{ ds.2 }})<br/>
              {% endfor %}
            </td>
          </tr>
        {% endif %}
        </tbody>
    </table>
    </div> {# right #}
	</div> {# row #}
</div> {# container #}

<script type="text/javascript">
    $("#edit_link").click(function () {
        $("#view_profile").toggle()
        $("#edit_profile").toggle()
        $("#edit_link").toggle()
    })
    $("#b_addgroup").click(function () {
        console.log('adding group')
    })
    $(".a_addmembers").click(function () {
        console.log('something simple for adding members to ' + $(this).data('id'))
    })

    function create_group() {
        var formData = new FormData()
        formData.append('ownerid', {{ user.id }})
        formData.append('title', $("#group_title").val())
        formData.append('description', "is this required?")
        formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        $.ajax({
            type: 'POST',
            enctype: 'multipart/form-data',
            url: '/collections/create_collection_group/',
            processData: false,
            contentType: false,
            cache: false,
            data: formData,
            success: function (response) {
                if (response.result == 'dupe') {
                    alert('That group name is taken')
                    $("input.action").prop('checked', false)
                } else {
                    res = response
                    if (res.status == "dupe") {
                        alert('that name is taken, try another')
                    } else {
                        // have to build an el here and add a click event to it
                        el = $('<a href="#" class="a_addmembers">' + res.name + '</a> (' + res.id + ')')
                        el.click(function () {
                            console.log($(this).text())
                        })
                        $("#grouplist").append(el)
                    }
                    $("#group_name").val('')
                    // $("#added_flash").fadeIn().delay(2000).fadeOut()
                    console.log('group created, click its name in group list to add members', res)
                    $("#groupform").hide()
                }
            }
        })
        $("#addtocoll").hide()
        $("#linkform_popup").hide()
    }
	</script>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'main/base.html' %}

{% block content %}
{% block extra_head %}
    <style>
        .fa-asterisk {font-size: .4rem !important; vertical-align: text-top;}
        th, td { padding: 2px 10px;}
    </style>
{% endblock %}
<div class="container">
  <div class="d-flex justify-content-center mt-3">
    <div class="justify-content-center">
    {% if error %} <p style="color:red">{{ error }}</p> {% endif %}
    <form method="post" action="{% url 'accounts:register' %}">
    <h2 class="">User Registration</h2>
      {% csrf_token %}
{#      <input type="hidden" name="first_name" value="n/a"/> <input type="hidden" name="last_name" value="n/a"/>#}
      <table>
        <tr><td class="">Email <i class="fa fa-asterisk "></i></td><td><input type="text" name="email" /></td></tr>
        <tr><td class="">Full name <i class="fa fa-asterisk "></i></td><td><input type="text" name="name" /></td></tr>
        <tr><td class="">Affiliation </td><td><input type="text" name="affiliation" /></td></tr>
        <tr><td class="">Web page </td><td><input type="text" name="web_page" /></td></tr>
          <tr><td class="">Password <i class="fa fa-asterisk "></i></td><td><input type="password" name="password1" /></td></tr>
          <tr>
              <td class="">Confirm password <i class="fa fa-asterisk "></i></td>
              <td><input type="password" name="password2" /></td></tr>
          <tr class="smaller">
              <td></td><td><i class="fa fa-asterisk "></i> required</td></tr>
      </table>
      <p class="mt-3">
        <input class="btn btn-primary" type="submit" value="Register"/>
      </p>

    </form>
  </div>
  </div>
</div>
<script type="text/javascript"></script>
{% endblock %}