api/urls.py
# api.urls

from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

# app_name = 'api'
# naming this app BREAKS DATATABLES IN DATASET BROWSE

urlpatterns = [

    # database places
    path('db/',views.SearchAPIView.as_view(),name='api-search'),
    # index docs
    path('index/',views.IndexAPIView.as_view(),name='api-index-search'),
    # index docs for remote
    path('remote/',views.RemoteIndexAPIView.as_view(),name='api-remote-search'),
    # spatial (nearby or bbox)
    path('spatial/', views.SpatialAPIView.as_view(), name='api-spatial'),

    # *** DATASETS ***

    # use: filter public datasets by id, label, term
    # 2022-09 name conflict with new remote api
    # path('datasets/', views.DatasetAPIView.as_view(), name='dataset-list'),
    path('datasets/', views.DatasetAPIView.as_view(), name='ds-list'),


    # *** PLACES ***
        
    # use: single place for ds_browse:: PlaceSerializer
    # also search.html if search scope = 'db'
    path('place/<int:pk>/', views.PlaceDetailAPIView.as_view(), name='place-detail'),

    # single place for record comparison in ds_update
    path('place_compare/<int:pk>/', views.PlaceCompareAPIView.as_view(), name='place-compare'),

    # places in a dataset
    # use: drf table in ds_browse  :: PlaceSerializer
    path('placetable/', views.PlaceTableViewSet.as_view({'get':'list'}), name='place-table'),
    # places in a collection
    path('placetable_coll/', views.PlaceTableCollViewSet.as_view({'get':'list'}), name='place-table-coll'), 

    # TODO: place/<str:dslabel>/<str:src_id>
    path('place/<str:dslabel>/<str:src_id>/', views.PlaceDetailSourceAPIView.as_view(),name='place-detail-src'), 


    # 
    # *** GEOMETRY ***
    # 
    # use: map in ds_browse, ds_places, collection_places :: PlaceGeomSerializer
    path('geoms/', views.GeomViewSet.as_view({'get':'list'}), name='geom-list'),
    # use: heatmap sources for collection_places.html
    path('geojson/', views.GeoJSONAPIView.as_view(), name='geojson'),    

    
    # 
    # *** AREAS ***
    # 
    # use: single area in dataset.html#addtask
    path('area/<int:pk>/', views.AreaViewSet.as_view({'get': 'retrieve'}),name='area-detail'),
    # returns list of simple objects (id, title) for home>autocomplete
    path('area_list/', views.AreaListView.as_view(),name='area-list'),
    # geojson for api
    path('area_features/', views.AreaFeaturesView.as_view(),name='area-features'), 
    
    # only UN regions, for teaching
    path('regions/', views.RegionViewSet.as_view(), name='regions'),

    # 
    # *** USERS ***
    #   
    path('users/', views.UserList.as_view(),name='user-list'),
    path('user/<int:pk>/', views.UserDetail.as_view(),name='user-detail'),
    
    # 
    # *** INDEX ***
    # 
    # use: single union record in usingapi.html ?idx=whg&_id={whg_id}
    # TODO: build from place_id
    #url('union/', views.indexAPIView.as_view(), name='union_api')
    
]

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'tsv', 'geojson'])

collection/urls.py
# collection.urls

from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from . import views
from traces.views import get_form, annotate

# area actions
app_name='collection'

urlpatterns = [

    # DATASET collections (datasets only)
    path('create_ds/', views.DatasetCollectionCreateView.as_view(), name='ds-collection-create'),
    path('<int:id>/update_ds', views.DatasetCollectionUpdateView.as_view(), name='ds-collection-update'),
    path('<int:pk>/summary_ds', views.DatasetCollectionSummaryView.as_view(), name='ds-collection-summary'),
    path('<int:id>/browse_ds', views.DatasetCollectionBrowseView.as_view(), name='ds-collection-browse'),

    # PLACE collections (datasets, indiv places, annotations, 'authored')
    path('create_pl/', views.PlaceCollectionCreateView.as_view(), name='place-collection-create'),
    path('<int:id>/update_pl', views.PlaceCollectionUpdateView.as_view(), name='place-collection-update'),
    path('<int:id>/browse_pl', views.PlaceCollectionBrowseView.as_view(), name='place-collection-browse'),
    path('flash_create/', views.flash_collection_create, name="collection-create-flash"),

    path('<int:id>/delete', views.CollectionDeleteView.as_view(), name='collection-delete'),

    # UTILITY
    path('list_ds/', views.ListDatasetView.as_view(), name='list-ds'),
    path('add_ds/<int:coll_id>/<int:ds_id>', views.add_dataset, name='add-ds'),
    path('remove_ds/<int:coll_id>/<int:ds_id>', views.remove_dataset, name='remove-ds'),

    path('add_places/', views.add_places, name="collection-add-places"),
    path('remove_places/', views.remove_places, name="collection-remove-places"),
    path('create_link/', views.create_link, name="collection-create-link"),
    path('remove_link/<int:id>/', views.remove_link, name="remove-link"),

    # function-based views to process a trace annotation
    path('<int:id>/annotate', csrf_exempt(annotate), name="collection-annotate"),
    path('annoform/', get_form, name="get_form"),

    # switch off active bit
    path('inactive/', views.inactive, name="collection-inactive"),

    path('<int:id>/geojson/', views.fetch_geojson_coll, name="geojson-coll"),

    ## COLLABORATORS
    # add CollectionUser collaborator
    path('collab-add/<int:collid>', views.collab_add, name="coll-collab-add"),

    # delete CollectionUser collaborator
    path('collab-delete/<int:uid>/<int:collid>', views.collab_delete, name="coll-collab-delete"),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

whg/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic.base import TemplateView

from main import views
from datasets.views import PublicListsView, DataListsView
from resources.views import TeachingPortalView

app_name='main'
#handler404 = 'datasets.views.handler404',
handler500 = 'main.views.custom_error_view'

urlpatterns = [
    path('', views.Home2b.as_view(), name="home"),
    
    path('libre/', views.LibreView.as_view(), name='libre'),
    
    # apps
    path('search/', include('search.urls')),
    path('datasets/', include('datasets.urls')),
    path('areas/', include('areas.urls')),
    path('collections/', include('collection.urls')),
    path('places/', include('places.urls')),
    path('elastic/', include('elastic.urls')),
    path('tutorials/', include('main.urls')),
    path('resources/', include('resources.urls')),
    path('teaching/', TeachingPortalView.as_view(), name="teaching-page"),

    # DEPRECATED
    # path('dashboard/', DashboardView.as_view(), name='dashboard'),

    ## DATA "DASHBOARD" LIST VIEWS
    # reverse name is parameter to DataListsView()
    path('mydata/', DataListsView.as_view(), name='data-datasets'),
    path('mycollections/', DataListsView.as_view(), name='data-collections'),
    path('mystudyareas/', DataListsView.as_view(), name='data-areas'),
    path('resourcelist/', DataListsView.as_view(), name='data-resources'),

    path('public_data/', PublicListsView.as_view(), name='public-lists'),

    # static content
    path('about/', TemplateView.as_view(template_name="main/about.html"), name="about"),
    path('contributing/', TemplateView.as_view(template_name="main/contributing.html"), name="contributing"),
    path('credits/', TemplateView.as_view(template_name="main/credits.html"), name="credits"),
    path('licensing/', TemplateView.as_view(template_name="main/licensing.html"), name="licensing"),
    path('system/', TemplateView.as_view(template_name="main/system.html"), name="system"),
    path('usingapi/', TemplateView.as_view(template_name="main/usingapi.html"), name="usingapi"),
    path('tinymce/', include('tinymce.urls')),

    path('comment/<int:rec_id>', views.CommentCreateView.as_view(), name='comment-create'),
    path('contact/', views.contact_view, name='contact'),
    path('success/', views.contact_success_view, name='success'),
    path('status/', views.status_view, name='status'),
    

    # backend stuff
    path('api/', include('api.urls')),
    path('remote/', include('remote.urls')),
    path('accounts/', include('allauth.urls')),
    #path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    # path('captcha/', include('captcha.urls')),

    re_path(r'^celery-progress/', include('celery_progress.urls')),  # the endpoint is configurable
    

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

collection/models.py
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.contrib.auth.models import User, Group
from django.contrib.postgres.fields import ArrayField #,JSONField
from django.core.validators import URLValidator
from django.urls import reverse
from datasets.models import Dataset
from main.choices import COLLECTIONCLASSES, LINKTYPES, TEAMROLES, STATUS_COLL
from places.models import Place
from django_resized import ResizedImageField

from .permissions import *
from tinymce.models import HTMLField

""" for images """
from io import BytesIO
import sys
from PIL import Image
from django.core.files.uploadedfile import InMemoryUploadedFile
""" end """
def collection_path(instance, filename):
  # upload to MEDIA_ROOT/collections/<coll id>/<filename>
  return 'collections/{0}/{1}'.format(instance.id, filename)

def user_directory_path(instance, filename):
  # upload to MEDIA_ROOT/user_<username>/<filename>
  return 'user_{0}/{1}'.format(instance.owner.username, filename)

def default_relations():
  return 'locale'.split(', ')
# needed b/c collection place_list filters on it
def default_omitted():
  return '{}'

class Collection(models.Model):
  owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                            related_name='collections', on_delete=models.CASCADE)
  title = models.CharField(null=False, max_length=255)
  description = models.TextField(max_length=3000)
  keywords = ArrayField(models.CharField(max_length=50), null=True)

  # array of place ids "removed" by user from the collection
  # filtered in collection.places_all and can't be annotated
  omitted = ArrayField(models.IntegerField(), blank=True, default=default_omitted)

  # per-collection relation keyword choices, e.g. waypoint, birthplace, battle site
  # need default or it errors for some reason
  rel_keywords = ArrayField(models.CharField(max_length=30), blank=True, null=True)
  # rel_keywords = ArrayField(models.CharField(max_length=30), blank=True, default=default_relations)

  # 3 new fields, 20210619
  creator = models.CharField(null=True, blank=True, max_length=500)
  contact = models.CharField(null=True, blank=True, max_length=500)
  webpage = models.URLField(null=True, blank=True)

  # modified, 20220902: no default
  collection_class = models.CharField(choices=COLLECTIONCLASSES, max_length=12)

  # single representative image
  image_file = ResizedImageField(size=[800, 600], upload_to=collection_path, blank=True, null=True)
  # single pdf file
  file = models.FileField(upload_to=collection_path, blank=True, null=True)

  created = models.DateTimeField(null=True, auto_now_add=True)
  # modified = models.DateTimeField(null=True)

  status = models.CharField(max_length=12, null=True, blank=True, choices=STATUS_COLL, default='sandbox')
  featured = models.IntegerField(null=True, blank=True)

  # collections can comprise >=0 datasets, >=1 places
  datasets = models.ManyToManyField("datasets.Dataset", blank=True)
  places = models.ManyToManyField("places.Place", blank=True)

  def get_absolute_url(self):
    #return reverse('datasets:dashboard', kwargs={'id': self.id})
    return reverse('data-collections')

  @property
  def collaborators(self):
    team_ids = self.collabs.values_list('user_id', flat=True)
    return User.objects.filter(id__in=team_ids) | User.objects.filter(groups__name='whg_team')

  # @property
  # def collaborators(self):
  #   team_ids = self.collabs.values_list('user_id', flat=True)
  #   return User.objects.filter(id__in=team_ids) | User.objects.filter(groups__name='whg_team')

  @property
  def owners(self):
    owner_ids = list(self.collabs.filter(role='owner').values_list('user_id', flat=True))
    owner_ids.append(self.owner_id)
    return User.objects.filter(id__in=owner_ids)

  @property
  def places_ds(self):
    dses = self.datasets.all()
    return Place.objects.filter(dataset__in=dses)

  @property
  def places_all(self):
    all = Place.objects.filter(
      Q(dataset__in=self.datasets.all()) | Q(id__in=self.places.all().values_list('id'))
    )
    return all.exclude(id__in=self.omitted)

  @property
  def ds_list(self):
    dsc = [{"id":d.id, "label":d.label, "bounds": d.bounds,
            "title":d.title, "modified": d.last_modified_text} for d in self.datasets.all()]
    dsp = [{"id":p.dataset.id, "label":p.dataset.label, "title":p.dataset.title #, "bounds": p.dataset.bounds
            ,"modified": p.dataset.last_modified_text
            } for p in self.places.all()]
    return list({ item['id'] : item for item in dsp+dsc}.values())

  @property
  def ds_counter(self):
    from collections import Counter
    from itertools import chain
    dc = self.datasets.all().values_list('label', flat=True)
    dp = self.places.all().values_list('dataset', flat=True)
    all = Counter(list(chain(dc, dp)))
    return dict(all)

  @property
  def last_modified_iso(self):
    # TODO: log entries for collections
    return self.created.strftime("%Y-%m-%d")

  @property
  def rowcount(self):
    dses = self.datasets.all()
    ds_counts = [ds.places.count() for ds in dses]
    return sum(ds_counts) + self.places.count()

  def __str__(self):
    return '%s:%s' % (self.id, self.title)

  class Meta:
    db_table = 'collections'
    permissions = [
      ("can_edit_collection", "Can edit collection"),
      ("can_delete_collection", "Can delete collection"),
      ("can_add_collaborator", "Can add collaborators"),
    ]

class CollectionLink(models.Model):
  collection = models.ForeignKey(Collection, default=None,
    on_delete=models.CASCADE, related_name='links')
  label = models.CharField(null=True, blank=True, max_length=200)
  uri = models.TextField(validators=[URLValidator()])
  link_type = models.CharField(default='page', max_length=10, choices=LINKTYPES)
  license = models.CharField(null=True, blank=True, max_length=64)

  def __str__(self):
    cap = self.label[:20]+('...' if len(self.label)>20 else '')
    return '%s:%s' % (self.id, cap)

  class Meta:
      managed = True
      db_table = 'collection_link'

class CollectionUser(models.Model):
  collection = models.ForeignKey(Collection, related_name='collabs',
                                   default=-1, on_delete=models.CASCADE)
  user = models.ForeignKey(User, related_name='coll_collab',
                                default=-1, on_delete=models.CASCADE)
  role = models.CharField(max_length=20, null=False, choices=TEAMROLES)

  def __str__(self):
    username = self.user.username
    return '<b>' + username + '</b> (' + self.role + ')'

  class Meta:
    managed = True
    db_table = 'collection_user'

# class CollectionGroup(models.Model):
#   owner = models.ForeignKey(settings.AUTH_USER_MODEL,
#                             related_name='classes', on_delete=models.CASCADE)
#   group = models.ForeignKey(Group, related_name='collection_group', on_delete=models.CASCADE)
#   title = models.CharField(null=False, max_length=1024)
#   description = models.CharField(null=False, max_length=2048)
#   keywords = ArrayField(models.CharField(max_length=50), null=True)
#
#   # a Collection can belong to >=1 CollectionGroup
#   collections = models.ManyToManyField("collection.Collection", blank=True)
#
#   def __str__(self):
#     return self.title
#
#   class Meta:
#     managed = True
#     db_table = 'collection_group'

""" not in use @v2.1; single image only """
class CollectionImage(models.Model):
  collection = models.ForeignKey(Collection, default=None,
    on_delete=models.CASCADE, related_name='images')
  image = models.FileField(upload_to=collection_path)
  caption = models.CharField(null=True, blank=True, max_length=500)
  uri = models.TextField(validators=[URLValidator()], null=True, blank=True)
  license = models.CharField(null=True, blank=True, max_length=64)

  def __str__(self):
    cap = self.caption[:20]+('...' if len(self)>20 else '')
    return '%s:%s' % (self.id, cap)

  class Meta:
      managed = True
      db_table = 'collection_image'

collection/templates/collection/collection_delete.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
  {% if user.id != object.owner.id and not user.is_superuser %}
    <p>Access to this page is limited to the collection owner(s)</p>
  {% else %}
  <div class="row justify-content-center">
    <div class="col-md-6 mt-5">
      <form action='' method='POST'>{% csrf_token %}
          <h3 class="text-danger">CAREFUL!!</h3>
          <p>This will delete the <b>{{ object.title }}</b> collection <b>definition</b>.</p>
          <p>It will <b>NOT</b> affect the datasets or places it includes!</p>
          <p class="mt-4">
            <input type='submit' value='Delete collection definition' />
            <a href="javascript:history.back()">Cancel</a>
          </p>
      </form>
    </div>
  </div>
  {% endif %}
</div>

{% endblock %}

collection/templates/collection/collection_group_delete.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-4 mt-5">
      <form action='' method='POST'>{% csrf_token %}
          <h3 class="text-danger">CAREFUL!!</h3>
          <p>This will destroy the <b>{{ object.title }} ({{ object.id }})</b> group, but leaves any associated collections and members intact.</p>
          <p class="mt-4">
            <input type='submit' value='Destroy' />
            <a href="javascript:history.back()">Cancel</a>
          </p>
      </form>
    </div>
  </div>
</div>

</div>
{% endblock %}

collection/templates/collection/collection_group_gallery.html
{% extends "main/base.html" %}
{% block title %}<title>{{ group }}p</title>{% endblock %}

{% block content %}

	{% load geojson_tags %}
	{% load leaflet_tags %}
	{% load static %}
	{% load dataset_extras %}
	{% block extra_head %}
	<style>
		#teaching_essay {height: 85%; overflow: auto; }
		#essay_modal {font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
			font-size: 1.2rem;}
		#main {
      position: relative;
      border: 1px solid black;
      border-radius: 8px;
      /* height: 100%; */
      width: 100%;
			overflow:hidden;
    }
		/* .leaflet-container-default {height: 250px !important;} */
		.gallery-banner-collections {border-bottom: 1px solid lightgray;
			background-color:#54A1DA; color: white;}
		.collection-gallery {
				background-color:rgb(238, 238, 238);
				overflow:auto; border-bottom: 1px solid gainsboro;}
		.coll-card {
				float:left;
				margin-right:.1rem;
				width: 33%;
				height: 175px;
				overflow-y:auto;
				background-color: white;}
		{#.coll-card:hover {cursor: pointer; opacity:0.8;}#}
		.coll-card-header {width:100%; background-color: honeydew;}
		.coll-card-content h6 {font-size: .9rem;}
		.coll-card-blurb {line-height: 1rem; font-size: small;}
		.regions-ttlink {color:grey; font-size:.75rem; float:right; text-decoration-line: underline;}
		.reset-link {float:right; display:none; color:white; text-decoration-line: underline;}
		#teaching_bottom {height:65%;}
		#teaching_top {height:230px;}
		.teaching-essay {outline: rgb(60, 136, 148) 1px solid; box-shadow: 4px 4px rgb(221, 221, 221);
			border-radius: 4px; background-color: ivory; min-height:auto; overflow-y: auto;}
		#badge_link { font-size:1rem; position:absolute; right:10px; z-index:100;}
		.fill-grey {background-color:gainsboro; }
		.fill-blue {background-color:rgb(60, 136, 148); }
		#region_label {font-family: 'Raleway', sans-serif !important; font-size:1rem; color: tomato;}
		.leaflet-container, .leaflet-container-default {min-height: 220px !important; max-height: 230px !important;}
	</style>
	{% endblock %}

	<div class="container pt-2 container-md" style="height: calc(100vh - 65px); position:relative;">
		<section class="text-center">
			<div class="container mb-1" style="position:relative">
				<h3>{{ group }} <span class="ital fs-6">{{ group.owner.name}}</span></h3>
			</div>
		</section>
		<div id="gallery_bottom" class="row mt-2">
			<div class="col-sm-12 pe-0" style="height: 85%;">
				<div class="collection-gallery h-100">
					<div class="gallery-banner-collections ps-2 small w-100";>ANNOTATED PLACE COLLECTIONS ({{ collections|length }})
						<span id="regions_reset" class="reset-link me-2" style="cursor:pointer;">reset filter</span>
					</div>
					<div class="ps-1">
						{% for c in collections %}
							<div class="coll-card mt-1">
								<div class="coll-card-content px-2 pt-1" data-id={{c.id}}>
									{% with remainder=190 %}
									<h6>
										<a href="{% url 'collection:place-collection-browse' c.id %}">{{ c.title }}</a>
										<br/><i>{{ c.owner.name }}</i><span class="float-end me-2 ital">{{ c.submit_date|date:'j M Y' }}</span>
									</h6>
									<p class="coll-card-blurb my-1">
										<img src="/media/{{ c.image_file.name }}" width="80" style="float: right;"/>
										{{ c.description|trunc_it:remainder }}
									</p>
									{%endwith%}
								</div>
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
		<div id="essay_modal" class="selector py-3" style="font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;"></div>
	</div>
	<script type="text/javascript">
		$(function () {
			$('[data-toggle="tooltip"]').tooltip()
			$("#regions_reset").click(function(){
				resetRegions()
			})
		})

		function resetRegions(){
			regions.setStyle({ fillColor: "#ff9999", color: "black" })
			$('.coll-card').css('display', 'block')
			$("#regions_reset").hide();
		}
		function filterResources(region){
			var $el = $('.coll-card').filter(function () {
				// console.log('this', $(this).data("regions"))
				return (!$(this).data("regions").includes(region))
			}).css('display','none')
			shown = $('.coll-card').filter(function(){
				return $(this).is(":visible");
			}) 
			regiones = []
			shown.each(function(){
				regarr = $(this).attr('data-regions').split(', ')
				// console.log('regset',regarr, typeof(regarr))
				regiones.push(regarr)
			})
			merged = [].concat.apply([], regiones);
			unique = [...new Set(merged.map(item => item))];
			$("#regions_reset").show();
		}

		// var dataurl = '{% url "area-features" %}';
		var dataurl = 'https://whgazetteer.org/api/area_features?filter=un';

		styles = {
				"MultiPolygon": {
					"default": { fillOpacity: 0.3, opacity: 1, color: "#000", weight: 1, fillColor: "#ff9999" },
					"focus": { fillOpacity: 0.3, opacity: 1, color: "red", weight: 2, fillColor: "#ff9999" }
				},
				"Polygon": {
					"default": { fillOpacity: 0.3, opacity: .5, color: "#666", weight: 1, fillColor: "#ff9999" },
					"focus": { fillOpacity: 0.3, opacity: .5, color: "red", weight: 2, fillColor: "#ff9999" }
				}
			}

		window.addEventListener("map:init", function (event) {
			map = event.detail.map;
			L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
				attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
			}).addTo(map);

			
			fetch(dataurl)
				.then(function (resp) {
					return resp.json();
				})
				.then(function (data) {
					// console.log(data)
					idToFeature = {}
					regions = L.geoJson(data, {
						filter: function (feature, layer) {
							return "{{ regions }}".includes(feature.properties.id);
						},
						onEachFeature: function onEachFeature(feature, layer) {
							// console.log('feature:', feature)
							identifier = feature.properties.id;
							layer.setStyle({ fillOpacity: .1, opacity: .5, color: "#000", weight: 1, fillColor: "#ff9999" })
							var props = feature.properties;
							// var content = `<b>${props.title}</b><p>${props.description}</p>`;
							var content = `<b>${props.title}</b>`;
							idToFeature[identifier] = layer
							// layer.bindPopup(content);
							layer.on('mouseover', function (e) {
								$("#region_label").html(content);
							});
							layer.on('mouseout', function (e) {
								$("#region_label").html("select region to filter")
							});							
							// layer.bindPopup(content);
						}
					}).addTo(map);
					
					L.Control.textbox = L.Control.extend({
						onAdd: function (map) {

							var textdiv = L.DomUtil.create('div');
							textdiv.id = "region_label";
							textdiv.innerHTML = "select region to filter"
							return textdiv;
						},

						onRemove: function (map) {
							// Nothing to do here
						}
					});
					L.control.textbox = function (opts) { return new L.Control.textbox(opts); }
					L.control.textbox({ position: 'topright' }).addTo(map);

					regions.on('click', function(e){
						// console.log('layer', e.layer)
						// show title in upper right
						$("#region_label").html(e.layer.feature.properties.title)
						// display all cards
						$('.resource-card').css('display', 'block')
						// default fill and outline for all regions
						regions.setStyle({fillColor:"#ff9999", color:"black"})
						// set fill for this to yellow
						e.layer.setStyle({fillColor:'yellow', color:"red"})
						// filter cards on region
						filterResources(e.layer.feature.properties.title)
						// title=e.layer.feature.properties.title
						// console.log('clicked region:',title)
					})
				});
		});
		$(function () {})
		// resources
		$(".resource-card-content").click(function(){
			rid = $(this).data('id');
			window.location.href = "/resources/"+rid+"/detail";
		})
		$(".modal-link").click(function () {
			page = $(this).data('id')
			$('.selector').dialog('open');
		})
		$(".selector").dialog({
				resizable: true,
				autoOpen: false,
				width: $(window).width() * 0.5,
				height: $(window).height() * 0.9,
				title: "Teaching with World Historical Gazetteer",
				modal: true,
				buttons: {
					'Close': function () {
						$(this).dialog('close');
					}
				},
				open: function (event, ui) {
					$('.selector').load('/media/resources/'+page+'.html');
				},
				show: { effect: "fade", duration: 400 },
				hide: { effect: "fade", duration: 400 }
			});

	</script>
{% endblock %}