api/urls.py
# api.urls

from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

# app_name = 'api'
# naming this app BREAKS DATATABLES IN DATASET BROWSE

urlpatterns = [

    # database places
    path('db/',views.SearchAPIView.as_view(),name='api-search'),
    # index docs
    path('index/',views.IndexAPIView.as_view(),name='api-index-search'),
    # index docs for remote
    path('remote/',views.RemoteIndexAPIView.as_view(),name='api-remote-search'),
    # spatial (nearby or bbox)
    path('spatial/', views.SpatialAPIView.as_view(), name='api-spatial'),

    # *** DATASETS ***

    # use: filter public datasets by id, label, term
    # 2022-09 name conflict with new remote api
    # path('datasets/', views.DatasetAPIView.as_view(), name='dataset-list'),
    path('datasets/', views.DatasetAPIView.as_view(), name='ds-list'),


    # *** PLACES ***
        
    # use: single place for ds_browse:: PlaceSerializer
    # also search.html if search scope = 'db'
    path('place/<int:pk>/', views.PlaceDetailAPIView.as_view(), name='place-detail'),

    # single place for record comparison in ds_update
    path('place_compare/<int:pk>/', views.PlaceCompareAPIView.as_view(), name='place-compare'),

    # places in a dataset
    # use: drf table in ds_browse  :: PlaceSerializer
    path('placetable/', views.PlaceTableViewSet.as_view({'get':'list'}), name='place-table'),
    # places in a collection
    path('placetable_coll/', views.PlaceTableCollViewSet.as_view({'get':'list'}), name='place-table-coll'), 

    # TODO: place/<str:dslabel>/<str:src_id>
    path('place/<str:dslabel>/<str:src_id>/', views.PlaceDetailSourceAPIView.as_view(),name='place-detail-src'), 


    # 
    # *** GEOMETRY ***
    # 
    # use: map in ds_browse, ds_places, collection_places :: PlaceGeomSerializer
    path('geoms/', views.GeomViewSet.as_view({'get':'list'}), name='geom-list'),
    # use: heatmap sources for collection_places.html
    path('geojson/', views.GeoJSONAPIView.as_view(), name='geojson'),    

    
    # 
    # *** AREAS ***
    # 
    # use: single area in dataset.html#addtask
    path('area/<int:pk>/', views.AreaViewSet.as_view({'get': 'retrieve'}),name='area-detail'),
    # returns list of simple objects (id, title) for home>autocomplete
    path('area_list/', views.AreaListView.as_view(),name='area-list'),
    # geojson for api
    path('area_features/', views.AreaFeaturesView.as_view(),name='area-features'), 
    
    # only UN regions, for teaching
    path('regions/', views.RegionViewSet.as_view(), name='regions'),

    # 
    # *** USERS ***
    #   
    path('users/', views.UserList.as_view(),name='user-list'),
    path('user/<int:pk>/', views.UserDetail.as_view(),name='user-detail'),
    
    # 
    # *** INDEX ***
    # 
    # use: single union record in usingapi.html ?idx=whg&_id={whg_id}
    # TODO: build from place_id
    #url('union/', views.indexAPIView.as_view(), name='union_api')
    
]

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'tsv', 'geojson'])

datasets/urls.py
# datasets.urls

from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views
from datasets.utils import download_file, UpdateCountsView, download_augmented, \
  fetch_geojson_ds, downloader, fetch_geojson_flat, downloadLP7

# dataset actions
app_name='datasets'
urlpatterns = [

  ## BASICS: create from upload, create empty, delete
  path('create/', views.DatasetCreateView.as_view(), name='dataset-create'),
  path('createnew/', views.DatasetCreateView.as_view(), name='dataset-create'),
  path('create_empty/', views.DatasetCreateEmptyView.as_view(), name='dataset-create-empty'),
  path('<int:id>/delete', views.DatasetDeleteView.as_view(), name='dataset-delete'),

  # insert validated delimited file data to db (csv, tsv, spreadsheet)
  path('<int:pk>/insert_tsv/', views.ds_insert_tsv, name="ds_insert_tsv"),

  # insert validated lpf file data to db
  path('<int:pk>/insert_lpf/', views.ds_insert_lpf, name="ds_insert_lpf"),

  # upload excel
  path('xl/', views.xl_upload, name='xl-upload'),

  ## MANAGE/VIEW
  # dataset owner pages (tabs); names correspond to template names
  path('<int:id>/summary', views.DatasetSummaryView.as_view(), name='ds_summary'),
  path('<int:id>/browse', views.DatasetBrowseView.as_view(), name='ds_browse'),
  path('<int:id>/reconcile', views.DatasetReconcileView.as_view(), name='ds_reconcile'),
  path('<int:id>/collab', views.DatasetCollabView.as_view(), name='ds_collab'),
  path('<int:id>/addtask', views.DatasetAddTaskView.as_view(), name='ds_addtask'),
  path('<int:id>/log', views.DatasetLogView.as_view(), name='ds_log'),

  # public dataset pages (tabs): metadata, browse
  path('<int:pk>', views.DatasetPublicView.as_view(), name='ds_meta'),
  path('<int:id>/places', views.DatasetPlacesView.as_view(), name='ds_places'),

  ## DOWNLOADS
  # one-off for LP7
  path('download_lp7/', downloadLP7, name='download_lp7'),

  # download latest file, as uploaded
  path('<int:id>/file/', download_file, name="dl-file"), #

  # initiate downloads of augmented datasets via celery task (called from ajax)
  path('dlcelery/', downloader, name='dl_celery'),
  ## DEPRECATing download augmented dataset
  path('<int:id>/augmented/<str:format>', download_augmented, name="dl-aug"), #

  ## UPDATES (in progress)
  path('compare/', views.ds_compare, name='dataset-compare'),
  path('update/', views.ds_update, name='dataset-update'),

  ## RECONCILIATION/REVIEW
  # initiate reconciliation
  path('<int:pk>/recon/', views.ds_recon, name="ds_recon"), # form submit

  # review, validate hits
  path('<int:pk>/review/<str:tid>/<str:passnum>', views.review, name="review"),

  # direct load of deferred place to review screen
  path('<int:pk>/review/<str:tid>/<str:pid>', views.review, name="review"),

  # accept any unreviewed wikidata pass0 hits from given task
  path('wd_pass0/<str:tid>', views.write_wd_pass0, name="wd_pass0"),
  path('idx_pass0/<str:tid>', views.write_idx_pass0, name="idx_pass0"),

  # delete TaskResult & associated hits
  path('task-delete/<str:tid>/<str:scope>', views.task_delete, name="task-delete"),

  # undo last save in review
  path('match-undo/<int:ds>/<str:tid>/<int:pid>', views.match_undo, name="match-undo"),

  # refresh reconciliation counts (ds.id from $.get)
  path('updatecounts/', UpdateCountsView.as_view(), name='update_counts'),

  ## COLLABORATORS
  # add DatasetUser collaborator
  path('collab-add/<int:dsid>/<str:v>', views.collab_add, name="collab-add"),

  # delete DatasetUser collaborator
  path('collab-delete/<int:uid>/<int:dsid>/<str:v>', views.collab_delete, name="collab-delete"),

  ## GEOMETRY
  path('<int:dsid>/geojson/', fetch_geojson_ds, name="geojson"),
  path('<int:dsid>/geojson_flat/', fetch_geojson_flat, name="geojson-flat"),

  # list places in a dataset; for physical geog layers
  path('<str:label>/places/', views.ds_list, name='ds_list'),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/urls.py
# main.urls

from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView
from resources.views import TeachingPortalView
from . import views

# actions
app_name='main'
urlpatterns = [

    path(r'', TemplateView.as_view(template_name="main/tutorials.html"), name="tutorials"),
    path('guide/', TemplateView.as_view(template_name="tutorials/guide.html"), name="tute-guide"),
    path('choosing/', TemplateView.as_view(template_name="tutorials/choosing.html"), name="tute-choosing"),
    path('collections/', TemplateView.as_view(template_name="tutorials/collections.html"), name="tute-collections"),
    path('contributing/', TemplateView.as_view(template_name="tutorials/contributing.html"), name="tute-contributing"),
    path('walkthrough/', TemplateView.as_view(template_name="tutorials/walkthrough.html"), name="tute-walkthrough"),
    path('placecollections/', TemplateView.as_view(template_name="tutorials/place_collections.html"), name="tute-place_collections"),
    path('create_lptsv/', TemplateView.as_view(template_name="tutorials/create_lptsv.html"), name="tute-lptsv"),
    path('teaching/', TeachingPortalView.as_view(), name="teaching-page"),

    path('modal/', TemplateView.as_view(template_name="main/modal.html"), name="dynamic-modal"),
]
#] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resources/urls.py
# resources.urls (for teaching)

from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

from . import views

# area actions
app_name = 'resources'

urlpatterns = [

    # resources/
    path('create/', views.ResourceCreateView.as_view(), name='resource-create'),
    # create handles create and update
    path('<int:id>/update', views.ResourceUpdateView.as_view(),
         name='resource-update'),
    path('<int:id>/delete', views.ResourceDeleteView.as_view(),
         name='resource-delete'),
    # detail is the public view
    path('<int:pk>/detail', views.ResourceDetailView.as_view(),
         name='resource-detail'),

    # teaching/
    path('', TemplateView.as_view(template_name="resources/teaching.html"), name="teaching-page"),
    path('asian_history/', TemplateView.as_view(
        template_name="resources/asian_history.html"), name="lesson-asian"),


    # path('list_ds/', views.ListDatasetView.as_view(), name='list-ds'),
    # path('remove_ds/<int:coll_id>/<int:ds_id>',
    #      views.remove_dataset, name='remove-ds'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

whg/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic.base import TemplateView

from main import views
from datasets.views import PublicListsView, DataListsView
from resources.views import TeachingPortalView

app_name='main'
#handler404 = 'datasets.views.handler404',
handler500 = 'main.views.custom_error_view'

urlpatterns = [
    path('', views.Home2b.as_view(), name="home"),
    
    path('libre/', views.LibreView.as_view(), name='libre'),
    
    # apps
    path('search/', include('search.urls')),
    path('datasets/', include('datasets.urls')),
    path('areas/', include('areas.urls')),
    path('collections/', include('collection.urls')),
    path('places/', include('places.urls')),
    path('elastic/', include('elastic.urls')),
    path('tutorials/', include('main.urls')),
    path('resources/', include('resources.urls')),
    path('teaching/', TeachingPortalView.as_view(), name="teaching-page"),

    # DEPRECATED
    # path('dashboard/', DashboardView.as_view(), name='dashboard'),

    ## DATA "DASHBOARD" LIST VIEWS
    # reverse name is parameter to DataListsView()
    path('mydata/', DataListsView.as_view(), name='data-datasets'),
    path('mycollections/', DataListsView.as_view(), name='data-collections'),
    path('mystudyareas/', DataListsView.as_view(), name='data-areas'),
    path('resourcelist/', DataListsView.as_view(), name='data-resources'),

    path('public_data/', PublicListsView.as_view(), name='public-lists'),

    # static content
    path('about/', TemplateView.as_view(template_name="main/about.html"), name="about"),
    path('contributing/', TemplateView.as_view(template_name="main/contributing.html"), name="contributing"),
    path('credits/', TemplateView.as_view(template_name="main/credits.html"), name="credits"),
    path('licensing/', TemplateView.as_view(template_name="main/licensing.html"), name="licensing"),
    path('system/', TemplateView.as_view(template_name="main/system.html"), name="system"),
    path('usingapi/', TemplateView.as_view(template_name="main/usingapi.html"), name="usingapi"),
    path('tinymce/', include('tinymce.urls')),

    path('comment/<int:rec_id>', views.CommentCreateView.as_view(), name='comment-create'),
    path('contact/', views.contact_view, name='contact'),
    path('success/', views.contact_success_view, name='success'),
    path('status/', views.status_view, name='status'),
    

    # backend stuff
    path('api/', include('api.urls')),
    path('remote/', include('remote.urls')),
    path('accounts/', include('allauth.urls')),
    #path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    # path('captcha/', include('captcha.urls')),

    re_path(r'^celery-progress/', include('celery_progress.urls')),  # the endpoint is configurable
    

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from places.models import Place
from datasets.models import Dataset

from main.choices import COMMENT_TAGS, COMMENT_TAGS_REVIEW, LOG_CATEGORIES, LOG_TYPES

# some log entries only user-related; most user- and dataset-related
class Log(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
        related_name='log', on_delete=models.CASCADE)
    dataset = models.ForeignKey(Dataset, null=True, blank=True, 
        related_name='log', on_delete=models.CASCADE)
    category = models.CharField(max_length=20, choices=LOG_CATEGORIES)
    logtype = models.CharField(max_length=20, choices=LOG_TYPES)
    subtype = models.CharField(max_length=50, null=True, blank=True)
    note = models.CharField(max_length=2044,null=True, blank=True)
    timestamp = models.DateTimeField(null=True, auto_now_add=True)
    
    class Meta:
        managed = True
        db_table = 'log'

# TODO: rename place_id to place; ramifications?
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
        related_name='comments', on_delete=models.CASCADE)
    place_id = models.ForeignKey(Place, on_delete=models.CASCADE)
    tag = models.CharField(max_length=20, choices=COMMENT_TAGS_REVIEW, default="other")
    note = models.CharField(max_length=2044, null=True, blank=True)
    created = models.DateTimeField(null=True, auto_now_add=True)

    @property
    def dataset(self):
        return self.place_id.dataset

    class Meta:
        managed = True
        db_table = 'comments'
    
    

main/forms.py
from django import forms
from django.db import models
from django.utils.safestring import mark_safe

from main.models import Comment
from main.choices import COMMENT_TAGS, COMMENT_TAGS_REVIEW
from bootstrap_modal_forms.forms import BSModalForm
# from captcha.fields import CaptchaField
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Checkbox

class ContactForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'size': 50}),
        required=True)
    username = forms.CharField(
        widget=forms.TextInput(attrs={'size': 50}),
        required=True)
    from_email = forms.EmailField(
        widget=forms.EmailInput(attrs={'size': 50}),
        required=True,
        label="Your email address ")
    subject = forms.CharField(
        widget=forms.TextInput(attrs={'size': 50}),
        required=True)
    message = forms.CharField(widget=forms.Textarea(attrs={'cols': 50, 'rows': 5}), required=True)
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)

class CommentModalForm(BSModalForm):
    class Meta:
        model = Comment
        # all fields: user, place_id, tag, note, created
        fields = ['tag', 'note','place_id']
        hidden_fields = ['created']
        exclude = ['user','place_id']
        widgets = {
            'place_id': forms.TextInput(),
            'tag': forms.RadioSelect(choices=COMMENT_TAGS, attrs={'class':'no-bullet'}),
            'note': forms.Textarea(attrs={
                'rows':2,'cols': 40,'class':'textarea'})
        }
        
    def __init__(self, *args, **kwargs):
        super(CommentModalForm, self).__init__(*args, **kwargs)  
        self.fields['tag'].label = "Issue"
        if '/def' in kwargs['initial']['next']:
            self.fields['tag'].choices = COMMENT_TAGS_REVIEW

main/templates/main/contributing.html
{% extends "main/base.html" %}
{% block title %}<title>WHG::Contributing</title>{% endblock %}
{% load static %}

{% block content %}
<div class="container">
  <div class="d-flex justify-content-center mt-3">
    <h3>Contributing to the World Historical Gazetteer</h3>
  </div>
  <div id="contrib_content" class="px-5">
    <h4>The Steps</h4>
    {% if user.is_authenticated %}
    <div id="tldr" class="float-end"><p class="mb-1">Okay, ready <br/>to <a href="{% url 'datasets:dataset-create' %}">begin!</a></div>{% endif %}
    <p>The contribution pipeline consists of the following four steps:</p>
    <ol>
      <li><b>Prepare data file(s)</b>. Make a transformation of your data from whatever format you keep it in to one of the Linked Places (LP) format "flavors" (details below)</li>
      <li><b>Upload data file(s)</b>. Your uploaded file(s) are checked for valid format. If valid, they are immediately inserted into WHG database. Your data is now maintained in a set of <i>read-only</i> tables [<a href="#">model documentation</a>], which are the basis for subsequent steps. Screens for managing the contribution and viewing it are now available</li>
      <li><b>Reconciliation against modern authorities</b>. It is essential that you find as many matches as possible between your records and modern gazetteer data resources prior to accessioning to WHG. Our reconciliation services can aid this process considerably in a two-part process:
        <ul><li><b>Initiate a reconciliation task</b> to find potential matches. At this time, Getty TGN and Wikidata are available. GeoNames and DBpedia will be added in the near future.</li>
        <li><b>Review the resulting "hits"</b>. Potential matches must be reviewed manually [1]. Our review tool queues them up for you and your team to decide whether a hit is a close match, exact match, or otherwise related. Each positive response augments your dataset by adding a record in the <i>place_link</i> table. You can also choose to augment your record with geometries from validated matches, where they exist, generating a new <i>place_geom</i> record.</li>
        </li></ul>
      <li><b>Accessioning</b> (i.e. reconciliation against WHG). Now it's time to see whether the places your records reference already exist in our index.
        <ul><li><b>Initiate the reconciliation task</b>. For the time being, WHG staff will perform this step after review of your potential contribution. NB: If a contributor's record shares a modern authority link with a record in our index, it is considered to be a match, and automatically becomes a "child" attestation within that WHG index record.</li>
        <li><b>Review potential matches</b>. The remaining hits, based on matches with some combination of names, place types, modern country, and geometry, must be reviewed as in step 3 above. When you assert a close or exact match between your record and one in the WHG index, your record is identified as a "child" record of the "parent" <i>in the index only</i>. If there is no match in the WHG index, your record becomes a new "parent," again, <i>in the index only</i></li>
        </ul>
      </li>
    </ol>
  </div>
  <div class="px-5">
    <h4>Contribution Format(s)</h4>
    <p>Two data formats can be used for contributions to WHG: (a) Linked Places format: JSON-LD and GeoJSON-T compatible, allowing for detailed sourcing of names and geometries, and temporal scoping of names, geometries, place types, and relations; and (b) an abbreviated TSV form appropriate for simpler records.</p>
    <div>
      <h5>Linked Places format [<a href="https://github.com/LinkedPasts/linked-places" target="_blank">details</a>]</h5>
      <p>Linked Places (LP) format is JSON-LD, a valid RDF syntax. It is also valid GeoJSON, which has been augmented with temporal support (GeoJSON-T). Version 1 of LP format is specified on <a href="https://github.com/LinkedPasts/linked-places" target = "_blank">this GitHub page</a>, and examples are provided.</p>
    </div>
    <div>
      <h5>TSV template [<a href="https://github.com/LinkedPasts/linked-places/blob/master/tsv.md" target="_blank">details</a>]</h5>
      <p>Not every dataset requires the expressiveness of LP format, so WHG will accept contributions in TSV format that follow <a href="https://github.com/LinkedPasts/linked-places/blob/master/tsv.md" target="_blank">these specifications</a>.</p>
      
    </div>
  </div>
{% if user.is_authenticated %}
  <!--<div class="px-5">-->
    <!--<p><button type="button" class="btn btn-primary">Begin </button></p>-->
  <!--</div>-->
</div>
{% endif %}
{% endblock %}

main/templates/main/tutorials.html
{% extends "main/base.html" %}
{% block title %}<title>WHG::Guides</title>{% endblock %}

{% block content %}

{% load static %}
{% block extra_head %}
<style>
  a.btn {background-color: aliceblue;}
</style>
{% endblock %}
<main role="main">

  <section class="text-center">
    <div class="container mb-1">
      <h3>Guides and Tutorials</h3>
    </div>
  </section>

  <div class="album py-3 bg-white">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div style="background-color:antiquewhite; height:10px;"></div>
            <img src="{% static 'images/tute_guide.png'%}" height="138">
            <div class="card-body">
              <h4>A Guide to WHG</h4>
              <p class="card-text">Overview, Page by Page details, FAQ </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'main:tute-guide' %}" class="btn btn-sm btn-outline-secondary" role="button">View</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div style="background-color:antiquewhite; height:10px;"></div>
            <div class="card-body">
              <h4>Navigating the WHG for Spatial Thinking</h4>
              <p class="card-text">A lesson plan using the World Historical Gazetteer to make connections 
                between named place and cartographic space, gaining exposure to key skills of spatial thinking and reasoning.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'resources:resource-detail' 8 %}" class="btn btn-sm btn-outline-secondary" role="button">View</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div style="background-color:antiquewhite; height:10px;"></div>
            <div class="card-body">
              <h4>Preparing an LP-TSV format file from a spreadsheet</h4>
              <p class="card-text">Step-by-step walkthrough from a spreadsheet to a valid LP-TSV file for upoad</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'main:tute-lptsv' %}" class="btn btn-sm btn-outline-secondary" role="button">View</a>
                  <span class="ms-3"></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div> <!-- .row -->
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div style="background-color:antiquewhite; height:10px;"></div>
            <div class="card-body">
              <h4>Walkthrough: Uploading and extending data via reconciliation</h4>
              <p class="card-text">Step by step tutorial for loading a sample dataset and aligning its records with 3.6m place records in our Wikidata index</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'main:tute-walkthrough' %}" class="btn btn-sm btn-outline-secondary" role="button">View</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div style="background-color:antiquewhite; height:10px;"></div>
            <div class="card-body">
              <h4>Creating and Publishing a Place Collection <span class="badge badge-warning ms-3">BETA</span></h4>
              <p class="card-text">A brief guide</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'main:tute-place_collections' %}" class="btn btn-sm btn-outline-secondary" role="button">View</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div style="background-color:antiquewhite; height:10px;"></div>
          <!--<img src="{ static 'images/blank_68h.png'%}" width="100%" height="40" >-->
            <div class="card-body">
              <h4>WHG Asian History Lesson: Exploring the Changing Names of Cities</h4>
              <p class="card-text">A sample lesson plan based on WHG</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'resources:lesson-asian' %}" class="btn btn-sm btn-outline-secondary" role="button">View</a>
                  <span class="ms-3"></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div> <!-- .row -->
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div style="background-color:antiquewhite; height:10px;"></div>
            <div class="card-body">
              <h4>Choosing an upload data format: Linked Places (LP) or LP-TSV?</h4>
              <p class="card-text">Outlining the benefits and drawbacks of each</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'main:tute-choosing' %}" class="btn btn-sm btn-outline-secondary" role="button">View</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div> <!-- .row -->
    </div>
  </div>
</main>

{% endblock %}